### ISSUE TITLE
KeyError: 'gene_regions' issue.

### ISSUE THREAD

**Issue by RoydenClark** [wbaopaul/scATAC-pro#30]
Greetings.
One of our researchers is trying to use scatac-pro but we continue to run into the following error:

configparser.NoOptionError: No option 'gene_regions' in section: 'mm10'

So I I think this is something we might be setting wrong in the configuration file but I am unable to determine the solution.

Can you please assist?

Royden

--------------------------------------------
Mon Nov 23 18:56:41 EST 2020
Footprint analysis ...
do all one-vs-rest comparison, this would take a very long time...
working on cluster 0 ...
construct regions by DA ...
predict footprint...
Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'gene_regions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Footprinting.py", line 134, in atac_seq
    genome_data = GenomeData(args.organism)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/Util.py", line 93, in __init__
    self.gene_regions = os.path.join(self.data_dir, self.config.get(organism, 'gene_regions'))
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gene_regions' in section: 'mm10'
Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'gene_regions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/bin/rgt-hint", line 8, in <module>
    sys.exit(main())
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Main.py", line 95, in main
    args.func(args)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Footprinting.py", line 110, in footprinting_run
    atac_seq(args)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/HINT/Footprinting.py", line 134, in atac_seq
    genome_data = GenomeData(args.organism)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/Util.py", line 93, in __init__
    self.gene_regions = os.path.join(self.data_dir, self.config.get(organism, 'gene_regions'))
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gene_regions' in section: 'mm10'
overlap with motif annotation ... 
>> output location: output/downstream_analysis/MACS2/FILTER/footprint/0_vs_rest

Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'gene_regions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/bin/rgt-motifanalysis", line 8, in <module>
    sys.exit(main())
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/motifanalysis/Main.py", line 58, in main
    args.func(args)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/motifanalysis/Match.py", line 145, in main
    genome_data = GenomeData(args.organism)
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/site-packages/rgt/Util.py", line 93, in __init__
    self.gene_regions = os.path.join(self.data_dir, self.config.get(organism, 'gene_regions'))
  File "/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'gene_regions' in section: 'mm10'
make: *** [/ri/shared/modules7/miniconda3/envs/scatac_pro-1.1.4/scATAC-pro/scATAC-pro_1.1.4/scripts/Makefile:253: footprint] Error 1

**Comment by wbaopaul** [comment]
The error should be due to the problem of the depedency for footprinting analysis. I guess this should be solved using the most latest version. Can you try the most latest version v1.2.0 instead of v1.1.4? Thanks.

**Comment by wbaopaul** [comment]
@RoydenClark Is your issue solved by using the updated version? If so, I am gonna close this issue since it has been inactive for a while.
